spring:
  datasource:
    url: jdbc:mysql://192.168.2.209:3306/vip?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: opsa
    password: pass123456
#  rabbitmq:
#    host: rabbitmq.znlhzl.org
#    port: 5672
#    username: admin
#    password: admin
#    virtual-host: /
#  redis:
#    host: redis.znlhzl.org
#    port: 6300
#    password: